# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d70467d30d9cc96d6b958bd5673d63ca64ebada7d5547a6aa1398c058ab6a58cc457de21ff1676db38040471f8d7daa9dbdfacc200294f3cbfab5a14ebf84d2b

test:
  secret_key_base: 1ac006fa24a3c0a276e07de2e42416cc119fac632eab9bcbf73d3064870403f095e7137aea9f6c4e59a823601848288e36efd9a08e9224f31d25aacd23984f03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
